Feature/esbuild
ministryofjustice/moj-flask-govuk-skeleton pull request #21
Opened 2024-12-17 08:11 UTC by psweeting1

2024-12-17 13:55 UTC, Pheonnexx approved these changes
LGTM

2024-12-17 15:25 UTC, BenMillar-MOJ requested changes

2024-12-17 15:25 UTC, BenMillar-MOJ commented on setup.cfg
> -exclude=venv
Can you exclude all virtual environment directories with `exclude=*venv, *env`

2024-12-18 08:29 UTC, TawneeOwl approved these changes
LGTM

2024-12-18 11:05 UTC, BenMillar-MOJ approved these changes

2024-12-18 11:12 UTC, merged